[package]
name = "torn-widgets"
description = "Standard widgets for Torn"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
torn-core = { path = "../torn-core" }
torn-render = { path = "../torn-render" }
torn-ui = { path = "../torn-ui" }
torn-workspace = { path = "../torn-workspace" }
